---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - { role: sshd, tags: ['sshd'] }
    - { role: devtools }
    - { role: epel }
    - { role: ntpd }
    - { role: firewalld, tags: ['firewalld'], when: private_files_repo_root is defined }

- hosts: pergenie_host
  become: yes
  gather_facts: yes
  roles:
    - { role: python }
    - { role: postgresql }
    - { role: rabbitmq }
    - { role: httpd, tags: ['httpd'] }
    - { role: pergenie, tags: ['pergenie'] }
