---
- name: restart wsgi
  become_user: "{{ app_user }}"
  command: touch {{ wsgi_dir }}/wsgi.py

- name: reload crontab
  become_user: "{{ app_user }}"
  command: crontab "/home/{{ app_user }}/crontab"

# TODO:
# http://docs.celeryproject.org/en/latest/reference/celery.bin.multi.html
- name: restart celery
  become_user: "{{ app_user }}"
  command: /apps/pergenie/.virtualenvs/pergenie/bin/celery multi restart 1 --app=pergenie --pidfile="{{ celery_pid_file }}" --logfile="{{ celery_log_file }}"
  args:
    chdir: /apps/pergenie/repo/pergenie
    creates:
      - /apps/pergenie/celery1.pid

# FIXME:
- name: stop celery
  become_user: "{{ app_user }}"
  command: /apps/pergenie/.virtualenvs/pergenie/bin/celery multi stop --pidfile="{{ celery_pid_file }}"
