---
- name: initdb
  command: /usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_version| replace('.', '') }}-setup initdb
           creates=/var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf

# - name: configure postgresql.conf
#   become_user: postgres
#   template:
#     src=postgresql.conf.j2
#     dest=/var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
#     owner=postgres group=postgres mode=0640

- name: configure pg_hba.conf
  become_user: postgres
  template:
    src=pg_hba.conf.j2
    dest=/var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf
    owner=postgres group=postgres mode=0640
  notify: restart postgresql

- name: start postgresql service
  service: name='postgresql-{{ postgresql_version }}' state=started enabled=yes
