---

# https://wiki.postgresql.org/wiki/YUM_Installation
- name: install postgresql repository
  yum: name={{ item }} state=present
  with_items:
   - "{{ postgresql_repo_url }}"

- name: install postgresql
  yum: name={{ item }} state=present
  with_items:
   - postgresql{{ postgresql_version| replace('.', '') }}-devel
   - postgresql{{ postgresql_version| replace('.', '') }}-server
   - postgresql{{ postgresql_version| replace('.', '') }}-contrib

- name: install psycopg2
  yum: name=python-psycopg2 state=present
