---
# https://www.rabbitmq.com/install-rpm.html

- name: install erlang
  yum: name=erlang state=present

- name: import gpg key
  rpm_key: key=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: install rabbitmq server
  yum: name={{ rpm_url }} state=present
  ignore_errors: yes

# TODO: configure

- name: start rabbitmq service
  service: name='rabbitmq-server' state=started enabled=yes
