---
# TODO: check state=present?
- name: django manage.py createsuperuser
  django_manage: command="createsuperuser --noinput --username={{ djnago_admin_user }} --email={{ django_admin_email }}"
                 virtualenv={{ virtualenv_dir }} app_path={{ app_root }} settings="pergenie.settings.{{ rollout_env }}"
  ignore_errors: yes

# TODO:
# - name: init_demo_user
#   django_manage: command="init_demo_user"
#                  virtualenv={{ virtualenv_dir }} app_path={{ app_root }} settings="pergenie.settings.{{ rollout_env }}"

# TODO:
# - name: update_gwascatalog
#   django_manage: command="update_gwascatalog"
#                  virtualenv={{ virtualenv_dir }} app_path={{ app_root }} settings="pergenie.settings.{{ rollout_env }}"
