---
# TODO: check state=present?
- name: django manage.py createsuperuser
  django_manage: command="createsuperuser --noinput --username={{ djnago_admin_user }} --email={{ django_admin_email }}"
                 virtualenv={{ virtualenv_dir }} app_path={{ app_root }} settings="pergenie.settings.{{ rollout_env }}"
  ignore_errors: yes

- django_manage: command={{ item }}
                 virtualenv={{ virtualenv_dir }} app_path={{ app_root }} settings="pergenie.settings.{{ rollout_env }}"
  with_items:
    - update_gwascatalog
    - setup_go_vcf_tools
    - init_demo_user
