---
- name: create app user
  user: name={{ app_user }}
  become: yes
  tags: common

- name: create postgresql user
  become_user: postgres
  postgresql_user: name={{ app_user }}
                   role_attr_flags=NOSUPERUSER
  tags: common

- name: create postgresql database
  become_user: postgres
  postgresql_db: name={{ database_name }}
                 encoding='UTF-8'
                 owner={{ app_user }}
  tags: common

# - name: clone repo
#   become_user: {{ app_user }}
#   git: repo={{ repo_url }}
#        dest={{ app_root }}
#   tags: install

- name: install python packages
  become_user: pergenie
  pip: virtualenv_command=/opt/python-2.7/bin/virtualenv
       virtualenv={{ app_root }}/.venv
       requirements={{ app_root }}/requirements.txt
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/pgsql-9.4/bin"

# TODO: set settings.py

- name: django migrate
  django_manage: virtualenv={{ app_root }}/.venv
                 app_path={{ app_root }}/pergenie
                 command=migrate
