---
- name: create app user
  user: name={{ app_user }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: create ssh-key for private files repo if exists
  user: name={{ app_user }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa_private_files_repo
  when: private_files_repo_url is defined

- name: create postgresql user
  become_user: postgres
  postgresql_user: name={{ database_user }}
                   password={{ database_pass }}
                   role_attr_flags=NOSUPERUSER

- name: create postgresql database
  become_user: postgres
  postgresql_db: name={{ database_name }}
                 encoding='UTF-8'
                 owner={{ database_user }}

- name: create project root dir
  file: path={{ proj_root }} state=directory mode=0755

- name: set build dir owner to app user
  file:
    path={{ build_root }} state=directory recurse=yes
    owner={{ app_user }} group={{ app_user }}

- name: create static root dir
  file: path={{ static_root }} state=directory mode=0755 recurse=yes owner={{ app_user }} group={{ app_user }}

- name: create upload root dir
  file: path={{ upload_root }} state=directory mode=0755 recurse=yes owner={{ app_user }} group={{ app_user }}

- include: rollout.yml
  become_user: "{{ app_user }}"
  notify: restart wsgi
  tags: rollout
