---
- name: create app user
  become: yes
  user: name={{ app_user }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: create postgresql user
  become_user: postgres
  postgresql_user: name={{ database_user }}
                   password={{ database_pass }}
                   role_attr_flags=NOSUPERUSER

- name: create postgresql database
  become_user: postgres
  postgresql_db: name={{ database_name }}
                 encoding='UTF-8'
                 owner={{ database_user }}

- name: create project root dir
  become: yes
  file: path={{ proj_root }} state=directory mode=0755

- name: set build dir owner to app user
  become: yes
  file:
    path={{ build_root }} state=directory recurse=yes
    owner={{ app_user }} group={{ app_user }}

# TODO: move bellow to rollout.yml

# FIXME:
- name: add github.com to known_hosts
  become_user: "{{ app_user }}"
  shell: ssh-keyscan github.com >> /home/{{ app_user }}/.ssh/known_hosts
  when: rollout_env == 'staging'

- name: clone repo
  become_user: "{{ app_user }}"
  git: repo={{ repo_url }}
       dest={{ proj_root }}
  tags: rollout

- name: create virtualenv and install python packages
  become_user: "{{ app_user }}"
  pip: virtualenv_command=virtualenv
       virtualenv={{ virtualenv_dir }}
       requirements={{ proj_root }}/requirements/{{ rollout_env }}.txt
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/pgsql-9.4/bin"
  tags: rollout

- name: configure settings.py
  become_user: "{{ app_user }}"
  template: src=settings.py.j2 dest="{{ wsgi_dir }}/settings/{{ rollout_env }}.py"
  tags: rollout

- name: django manage.py migrate
  become_user: "{{ app_user }}"
  django_manage: virtualenv={{ virtualenv_dir }}
                 app_path={{ app_root }}
                 command=migrate
  tags: rollout
  notify: restart wsgi

# TODO: $ python manage.py createsuperuser
#       $ python manage.py update_gwascatalog
#       $ python manage.py init_demo_user

# TODO: add `notify: restart wsgi` at last command
