---
- name: create app user
  user: name={{ app_user }}
  become: yes
  tags: init

- yum: name=python-psycopg2 state=present
  tags: init

- name: create postgresql user
  become_user: postgres
  postgresql_user: name={{ app_user }}
                   role_attr_flags=NOSUPERUSER
  tags: init

- name: create postgresql database
  become_user: postgres
  postgresql_db: name={{ database_name }}
                 encoding='UTF-8'
                 owner={{ app_user }}
  tags: init

- name: create django project root
  become: yes
  file: path={{ proj_root }} state=directory mode=0755
  tags: init

- name: set build dir owner to app user
  become: yes
  file: path={{ build_root }} state=directory recurse=yes owner={{ app_user }}
  tags: init

- name: clone repo
  become_user: "{{ app_user }}"
  git: repo={{ repo_url }}
       dest={{ proj_root }}
  tags: rollout

- name: install python packages
  become_user: {{ app_user }}
  pip: virtualenv_command=/opt/python-2.7/bin/virtualenv
       virtualenv={{ virtualenv_dir }}
       requirements={{ proj_root }}/requirements.txt
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/pgsql-9.4/bin"
  tags: rollout

# TODO: set settings.py

- name: django migrate
  django_manage: virtualenv={{ virtualenv_dir }}
                 app_path={{ app_root }}
                 command=migrate
  tags: rollout
